basePath: /
definitions:
  delivery.ErrorResponse:
    description: Ответ с ошибкой
    properties:
      error:
        properties:
          code:
            type: string
          message:
            type: string
        type: object
    type: object
  delivery.TeamRequest:
    description: Запрос на создание команды с участниками
    properties:
      members:
        items:
          $ref: '#/definitions/delivery.UserRequest'
        type: array
      team_name:
        type: string
    required:
    - team_name
    type: object
  delivery.TeamResponse:
    description: Ответ с информацией о команде
    properties:
      team:
        $ref: '#/definitions/domain.Team'
    type: object
  delivery.UserRequest:
    description: Запрос на создание пользователя в команде
    properties:
      is_active:
        type: boolean
      user_id:
        type: string
      username:
        type: string
    type: object
  domain.Team:
    description: Команда с участниками
    properties:
      members:
        items:
          $ref: '#/definitions/domain.User'
        type: array
      team_name:
        type: string
    type: object
  domain.User:
    description: Пользователь системы
    properties:
      is_active:
        type: boolean
      team_name:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://localhost:8080/swagger/index.html
  description: This is PR Service.
  title: PR Service
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Проверяет, что сервис работает корректно
      produces:
      - application/json
      responses:
        "200":
          description: Статус сервиса
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Проверка здоровья сервиса
      tags:
      - Health
  /team/add:
    post:
      consumes:
      - application/json
      description: Создает новую команду и обновляет/создает пользователей. Если команда
        уже существует, возвращает ошибку.
      parameters:
      - description: Данные команды
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/delivery.TeamRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Команда успешно создана
          schema:
            $ref: '#/definitions/delivery.TeamResponse'
        "400":
          description: Неверный запрос или команда уже существует
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Создать команду с участниками
      tags:
      - Teams
  /team/get:
    get:
      consumes:
      - application/json
      description: Возвращает информацию о команде и ее участниках по имени команды
      parameters:
      - description: Уникальное имя команды
        example: '"payments"'
        in: query
        name: team_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Информация о команде
          schema:
            $ref: '#/definitions/domain.Team'
        "400":
          description: Не указано имя команды
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "404":
          description: Команда не найдена
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Получить команду с участниками
      tags:
      - Teams
swagger: "2.0"
